# Generated by Django 3.0.4 on 2020-03-06 18:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('item_type', models.CharField(max_length=120)),
                ('img_info', jsonfield.fields.JSONField()),
                ('notes', jsonfield.fields.JSONField()),
                ('quests', jsonfield.fields.JSONField()),
                ('hideout', jsonfield.fields.JSONField()),
            ],
        ),
    ]
