# Generated by Django 3.0.4 on 2020-03-08 07:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200306_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
